services:
  web:
    build: .
    image: anguspllg/outfitter_web:latest
    container_name: outfiter_web
    restart: unless-stopped
    volumes:
      - ./assets:/app/assets:Z
    depends_on:
      - db
      - valkey
      - image_processing
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - VALKEY_HOST=valkey
    ports:
      - '4173:3000'

  image_processing:
    image: anguspllg/outfitter_image_processing:latest
    container_name: outfitter_image_processing
    restart: unless-stopped
    environment:
      - FRONTEND_ORIGIN=${ORIGIN}
      - API_KEY=${IMAGE_PROCESSING_API_KEY}

  db:
    image: postgres:18.1
    container_name: outfiter_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  valkey:
    container_name: outfiter_valkey
    image: valkey/valkey:9.0.1
    command: valkey-server --save 60 1 --loglevel debug
    volumes:
      - valkey-data:/data

volumes:
  pg_data:
  valkey-data:
