services:
  web:
    build: .
    image: anguspllg/outfitter_web:latest
    container_name: outfiter_web
    restart: unless-stopped
    volumes:
       - ./assets:/app/assets:Z
    depends_on:
      - db
      - redis
      - image_processing
    environment:
      - ORIGIN=http://localhost:4173
    env_file:
      - .env
    ports:
      - '4173:3000'

  image_processing:
    image: anguspllg/outfitter_image_processing:latest
    container_name: outfitter_image_processing
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - FRONTEND_ORIGIN=http://localhost:4173
      - API_KEY=${IMAGE_PROCESSING_API_KEY}

  db:
    image: postgres
    container_name: outfiter_db
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z

  redis:
    container_name: outfiter_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pg_data:
